/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:b640dfb5-1406-4b46-81d3-2fc65e1ee0a0",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_UBFYyqI79",
    "aws_user_pools_web_client_id": "7o9sjcg8rkernkt8vopvslqsus",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://omt42jfdznejrhziouybwudiu4.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
