/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:4ec5ef93-0bcb-49e7-b20a-51c2fc4104f2",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_R59f9DBSh",
    "aws_user_pools_web_client_id": "59s7lrv67tv9q9r5jv4idtmb5b",
    "oauth": {}
};


export default awsmobile;
