/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:9c666229-0d46-484f-8c34-e378ee2ce854",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_pZo4rpeDQ",
    "aws_user_pools_web_client_id": "17pb05isjlamq95cghl3mcu7j9",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://wxipvhazqbff3cn33qbylblm5q.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
